compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs

supportedArchitectures:
    os: ['current', 'linux', 'darwin']
    cpu:
        - 'current'
        - 'x64'
        - 'arm64'
