import './global.css';
import { TRPCProvider } from '../lib/trpc/Provider';

export const metadata = {
  title: 'Twin Cities Marathon',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TRPCProvider>{children}</TRPCProvider>
      </body>
    </html>
  );
}
